### ISSUE TITLE
Docker-compose Login failed

### ISSUE THREAD

**Issue by rastogiujj12** [john-titor-master/bombcrypto-superbot#82]
Hey, I am getting LoginFailed error when using docker-compose. It works fine on telegram bot so I believe its issue with my docker-compose-local.yml

I am doing 

```
version: "3.4"

services:
  bomb1:
    image: vieceli/bombcrypto-superbot:latest
    restart: always
    working_dir: "/bombcrypto-superbot"
    environment:
      LOGIN: "user:mylogin:mypassword"
      TELEGRAM_KEY: ""
    volumes:
      - ./csv:/bombcrypto-superbot/csv
```

thanks
